"""Add last_reset_request_at to User

Revision ID: 4f5821ffac8e
Revises: 6db86c01adaf
Create Date: 2026-05-26 21:25:14.491718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5821ffac8e'
down_revision = '6db86c01adaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reset_request_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_reset_request_at')

    # ### end Alembic commands ###
