"""Add priority_order and bilingual columns

Revision ID: 93b777e574b3
Revises: 4f5821ffac8e
Create Date: 2026-05-28 11:12:27.958474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b777e574b3'
down_revision = '4f5821ffac8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_evaluation_tr', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_evaluation_en', sa.Text(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('priority_order')

    with op.batch_alter_table('ai_suggestions', schema=None) as batch_op:
        batch_op.drop_column('ai_evaluation_en')
        batch_op.drop_column('ai_evaluation_tr')

    # ### end Alembic commands ###
