import os
import re

new_translations = {
    "en": {
        "Gemini %(model_name)s Aktif": "Gemini %(model_name)s Active",
        "AI Simülasyon Modu Aktif": "AI Simulation Mode Active",
        "Geçmişi Temizle": "Clear Chat History",
        "AI Simülasyon Modu:": "AI Simulation Mode:",
        "Şu an sunucuda bir Gemini API Anahtarı girilmediği için çevrimdışı simülasyon modu aktiftir. Asistana selam verebilir, planınızı sıralamasını veya çakışmaları bulmasını isteyebilirsiniz. Gerçek üretken yapay zekayı denemek için .env dosyanıza GEMINI_API_KEY ekleyebilirsiniz.": "Offline simulation mode is active because no Gemini API Key is entered on the server. You can say hello to the assistant, ask it to sort your plan or find conflicts. To try real generative AI, you can add GEMINI_API_KEY to your .env file.",
        "Merhaba <strong>%(username)s</strong>! Ben senin akıllı planlama asistanın <strong>Glide AI</strong>.": "Hello <strong>%(username)s</strong>! I am your smart planning assistant <strong>Glide AI</strong>.",
        "Bugün yapılacak tüm görevlerini inceledim. Günlük işlerini planlamak, saat çakışmalarını çözmek veya o anki motivasyonuna göre zaman çizelgeni düzenlemek için buradayım.": "I have reviewed all your tasks for today. I am here to plan your daily work, resolve time conflicts, or organize your timeline based on your current motivation.",
        "Bugün kendini nasıl hissediyorsun? Günün en verimli saatlerini hangi işlere ayırmak istersin? Yaz bana, planını karşılıklı konuşarak güncelleyelim!": "How are you feeling today? Which tasks would you like to allocate your most productive hours to? Write to me, let's update your plan interactively!",
        "Günlük planımdaki saat çakışmalarını kontrol eder misin?": "Could you check the time conflicts in my daily plan?",
        "Çakışmaları Bul": "Find Conflicts",
        "Görevlerimi öncelik sırasına göre dizer misin?": "Could you sort my tasks by priority?",
        "Görevleri Sırala": "Sort Tasks",
        "Bugünkü planımı optimize etmek ve verimlilik tavsiyesi almak istiyorum.": "I want to optimize my plan for today and get productivity advice.",
        "Verimlilik Önerileri": "Productivity Tips",
        "Bugün kendimi biraz yorgun hissediyorum, planımı esnek periyotlara çeker misin?": "I feel a bit tired today, could you adjust my plan to flexible periods?",
        "Esnek Plan İstiyorum": "I Want Flexible Plan",
        "Asistan ile konuşun, planınızı isteyin...": "Talk to the assistant, ask for your plan...",
        "Sohbet geçmişinizi tamamen temizlemek istediğinize emin misiniz?": "Are you sure you want to completely clear your chat history?",
        "Hata:": "Error:",
        "İşlem gerçekleştirilemedi.": "Operation could not be performed.",
        "Bir hata oluştu": "An error occurred",
        "Bir hata oluştu.": "An error occurred.",
        "AI Asistanı": "AI Assistant",
        "Planlama Asistanı": "Planning Assistant",
        "AI Akıllı Planlayıcı": "AI Smart Planner",
        "Yapay zeka tarafından üretilen zaman analizi ve verimlilik önerileri.": "AI-generated time analysis and productivity suggestions.",
        "Analizi Yenile": "Refresh Analysis",
        "Yapay Zeka Analiz Raporu": "AI Analysis Report",
        "Oluşturulma Zamanı:": "Created At:",
        "Henüz Bir Rapor Yok": "No Report Yet",
        "Zaman planınızı optimize etmek ve çakışma raporu almak için lütfen analizi başlatın.": "Please start the analysis to optimize your schedule and get conflict reports.",
        "Akıllı Öncelik Sıralaması": "Smart Priority Sequence",
        "Görevleriniz, yapay zekanın önerdiği şekilde periyot, öncelik derecesi ve saat baz alınarak verimlilik odaklı sıralanmıştır.": "Your tasks are sorted by period, priority and time for efficiency, as recommended by AI.",
        "Görev Tanımlanmamış": "No Tasks Defined",
        "Öncelik sıralaması görebilmek için önce görevlerinizi ekleyin.": "Add your tasks first to see their priority sequence.",
        "örn. Python Projesi Hazırla": "e.g. Prepare Python Project",
        "Görev detaylarını buraya yazın...": "Enter task details here...",
        "Tümü": "All",
        "Öncelik:": "Priority:",
        "\\%(query)s\\ için arama sonuçları": "Search results for \"%(query)s\"",
        "Bu görevi silmek istediğinize emin misiniz?": "Are you sure you want to delete this task?",
        "Aradığınız kriterlere uygun görev bulunamadı": "No tasks found matching your criteria",
        "Lütfen arama teriminizi değiştirip tekrar deneyin.": "Please change your search term and try again.",
        "Yeni planlar yapmak için sol paneldeki görev formunu kullanabilirsiniz.": "You can use the task form on the left panel to make new plans.",
        "Sunucuyla bağlantı kurulurken hata oluştu.": "An error occurred while connecting to the server.",
        "Hesabınıza erişmek için bilgilerinizi girin.": "Enter your credentials to access your account.",
        "kullanici_adi": "username",
        "Kullanmaya başlamak için kaydolun.": "Sign up to start using the application.",
        "Zaten üye misiniz?": "Already a member?",
        "Giriş Yapın": "Log In",
        "Hesabınızın kayıtlı e-posta adresini girin.": "Enter your registered email address.",
        "Sıfırlama Bağlantısı Gönder": "Send Reset Link",
        "Giriş Sayfasına Dön": "Return to Login Page",
        "Yeni Şifre Belirle": "Set New Password",
        "Hesabınız için yeni ve güçlü bir şifre girin.": "Enter a new and strong password for your account.",
        "Yeni Şifre": "New Password",
        "Şifremi Güncelle": "Update Password",
        "Ups! Bir şeyler ters gitti.": "Oops! Something went wrong.",
        "Panelime Git": "Go to My Dashboard",
        "Yapay Zeka Destekli Planlayıcı": "AI-Powered Planner",
        "Yapay Zeka Destekli Akıllı Zaman Yönetimi": "AI-Powered Smart Time Management",
        "Zamanınızı": "Reshape Your",
        "Yapay Zeka": "Time with",
        "ile Yeniden Şekillendirin": "Artificial Intelligence",
        "Spagetti kodlardan arınmış, modüler Flask mimarisiyle geliştirilmiş; çakışma analizleri ve kişiselleştirilmiş verimlilik önerileri sunan dönem projesi.": "A term project built on modular Flask architecture, free from spaghetti code, featuring conflict analysis and personalized productivity tips.",
        "Hemen Ücretsiz Başla": "Get Started Free",
        "AI Zaman Asistanı": "AI Time Assistant",
        "AKTİF": "ACTIVE",
        "Dönem Projesi Teslimi": "Term Project Delivery",
        "Yapay Zeka Uyarısı:": "AI Alert:",
        "Zamanlama planınızda herhangi bir çakışma bulunmamaktadır. Günlük hedeflerinize ulaşmak için hazırsınız!": "There are no conflicts in your schedule. You are ready to achieve your daily goals!",
        "Profil Fotoğrafını Değiştir": "Change Profile Picture",
        "Fotoğraf Seç": "Choose Photo",
        "Dosya seçilmedi": "No file selected",
        "Desteklenen formatlar: PNG, JPG, JPEG, GIF (Maks. 2MB)": "Supported formats: PNG, JPG, JPEG, GIF (Max. 2MB)",
        "Değişiklikleri Kaydet": "Save Changes",
        "AI Sohbet Asistanı": "AI Chat Assistant",
        " Flask Uygulamasını Sun": "Present Flask Application",
        "Panele Geri Dön": "Back to Dashboard"
    },
    "fr": {
        "Gemini %(model_name)s Aktif": "Gemini %(model_name)s Actif",
        "AI Simülasyon Modu Aktif": "Mode Simulation IA Actif",
        "Geçmişi Temizle": "Effacer l'historique",
        "AI Simülasyon Modu:": "Mode Simulation IA :",
        "Şu an sunucuda bir Gemini API Anahtarı girilmediği için çevrimdışı simülasyon modu aktiftir. Asistana selam verebilir, planınızı sıralamasını veya çakışmaları bulmasını isteyebilirsiniz. Gerçek üretken yapay zekayı denemek için .env dosyanıza GEMINI_API_KEY ekleyebilirsiniz.": "Le mode de simulation hors ligne est actif car aucune clé API Gemini n'a été saisie sur le serveur. Vous pouvez dire bonjour à l'assistant, lui demander de trier votre planning ou de trouver des conflits. Pour essayer la véritable IA générative, vous pouvez ajouter GEMINI_API_KEY à votre fichier .env.",
        "Merhaba <strong>%(username)s</strong>! Ben senin akıllı planlama asistanın <strong>Glide AI</strong>.": "Bonjour <strong>%(username)s</strong> ! Je suis votre assistant de planification intelligent <strong>Glide AI</strong>.",
        "Bugün yapılacak tüm görevlerini inceledim. Günlük işlerini planlamak, saat çakışmalarını çözmek veya o anki motivasyonuna göre zaman çizelgeni düzenlemek için buradayım.": "J'ai passé en revue toutes vos tâches d'aujourd'hui. Je suis ici pour planifier votre travail quotidien, résoudre les conflits horaires ou organiser votre emploi du temps selon votre motivation du moment.",
        "Bugün kendini nasıl hissediyorsun? Günün en verimli saatlerini hangi işlere ayırmak istersin? Yaz bana, planını karşılıklı konuşarak güncelleyelim!": "Comment vous sentez-vous aujourd'hui ? À quelles tâches aimeriez-vous consacrer vos heures les plus productives ? Écrivez-moi, mettons à jour votre planning ensemble !",
        "Günlük planımdaki saat çakışmalarını kontrol eder misin?": "Pouvez-vous vérifier les conflits horaires dans mon planning quotidien ?",
        "Çakışmaları Bul": "Trouver des Conflits",
        "Görevlerimi öncelik sırasına göre dizer misin?": "Pouvez-vous trier mes tâches par priorité ?",
        "Görevleri Sırala": "Trier les Tâches",
        "Bugünkü planımı optimize etmek ve verimlilik tavsiyesi almak istiyorum.": "Je souhaite optimiser mon planning d'aujourd'hui et obtenir des conseils de productivité.",
        "Verimlilik Önerileri": "Conseils de Productivité",
        "Bugün kendimi biraz yorgun hissediyorum, planımı esnek periyotlara çeker misin?": "Je me sens un peu fatigué aujourd'hui, pouvez-vous adapter mon planning à des périodes flexibles ?",
        "Esnek Plan İstiyorum": "Je veux un planning flexible",
        "Asistan ile konuşun, planınızı isteyin...": "Parlez à l'assistant, demandez votre planning...",
        "Sohbet geçmişinizi tamamen temizlemek istediğinize emin misiniz?": "Êtes-vous sûr de vouloir effacer complètement votre historique de discussion ?",
        "Hata:": "Erreur :",
        "İşlem gerçekleştirilemedi.": "L'opération n'a pas pu être effectuée.",
        "Bir hata oluştu": "Une erreur est survenue",
        "Bir hata oluştu.": "Une erreur est survenue.",
        "AI Asistanı": "Assistant IA",
        "Planlama Asistanı": "Assistant de Planification",
        "AI Akıllı Planlayıcı": "Planificateur Intelligent IA",
        "Yapay zeka tarafından üretilen zaman analizi ve verimlilik önerileri.": "Analyses de temps et recommandations de productivité générées par l'IA.",
        "Analizi Yenile": "Actualiser l'Analyse",
        "Yapay Zeka Analiz Raporu": "Rapport d'Analyse IA",
        "Oluşturulma Zamanı:": "Créé à :",
        "Henüz Bir Rapor Yok": "Aucun Rapport",
        "Zaman planınızı optimize etmek ve çakışma raporu almak için lütfen analizi başlatın.": "Veuillez lancer l'analyse pour optimiser votre emploi du temps et obtenir des rapports de conflit.",
        "Akıllı Öncelik Sıralaması": "Tri Intelligent par Priorité",
        "Görevleriniz, yapay zekanın önerdiği şekilde periyot, öncelik derecesi ve saat baz alınarak verimlilik odaklı sıralanmıştır.": "Vos tâches sont triées par période, priorité et heure pour plus d'efficacité, comme recommandé par l'IA.",
        "Görev Tanımlanmamış": "Aucune Tâche Définie",
        "Öncelik sıralaması görebilmek için önce görevlerinizi ekleyin.": "Ajoutez d'abord vos tâches pour voir leur ordre de priorité.",
        "örn. Python Projesi Hazırla": "ex. Préparer le Projet Python",
        "Görev detaylarını buraya yazın...": "Écrivez les détails de la tâche ici...",
        "Tümü": "Tout",
        "Öncelik:": "Priorité :",
        "\\%(query)s\\ için arama sonuçları": "Résultats de recherche pour \"%(query)s\"",
        "Bu görevi silmek istediğinize emin misiniz?": "Êtes-vous sûr de vouloir supprimer cette tâche ?",
        "Aradığınız kriterlere uygun görev bulunamadı": "Aucune tâche correspondant à vos critères n'a été trouvée",
        "Lütfen arama teriminizi değiştirip tekrar deneyin.": "Veuillez modifier votre terme de recherche et réessayer.",
        "Yeni planlar yapmak için sol paneldeki görev formunu kullanabilirsiniz.": "Vous pouvez utiliser le formulaire de tâche dans le panneau de gauche pour créer de nouveaux plans.",
        "Sunucuyla bağlantı kurulurken hata oluştu.": "Une erreur s'est produite lors de la connexion au serveur.",
        "Hesabınıza erişmek için bilgilerinizi girin.": "Entrez vos informations pour accéder à votre compte.",
        "kullanici_adi": "nom_d_utilisateur",
        "Kullanmaya başlamak için kaydolun.": "Inscrivez-vous pour commencer à utiliser l'application.",
        "Zaten üye misiniz?": "Déjà membre ?",
        "Giriş Yapın": "Se Connecter",
        "Hesabınızın kayıtlı e-posta adresini girin.": "Entrez l'adresse e-mail enregistrée de votre compte.",
        "Sıfırlama Bağlantısı Gönder": "Envoyer le Lien de Réinitialisation",
        "Giriş Sayfasına Dön": "Retour à la Page de Connexion",
        "Yeni Şifre Belirle": "Définir un Nouveau Mot de Passe",
        "Hesabınız idin yeni ve güçlü bir şifre girin.": "Entrez un mot de passe fort et nouveau pour votre compte.",
        "Yeni Şifre": "Nouveau Mot de Passe",
        "Şifremi Güncelle": "Mettre à Jour le Mot de Passe",
        "Ups! Bir şeyler ters gitti.": "Oups ! Quelque chose a mal tourné.",
        "Panelime Git": "Aller à Mon Tableau de Bord",
        "Yapay Zeka Destekli Planlayıcı": "Planificateur IA",
        "Yapay Zeka Destekli Akıllı Zaman Yönetimi": "Gestion du Temps IA",
        "Zamanınızı": "Redessinez avec",
        "Yapay Zeka": "l'IA votre",
        "ile Yeniden Şekillendirin": "temps",
        "Spagetti kodlardan arınmış, modüler Flask mimarisiyle geliştirilmiş; çakışma analizleri ve kişiselleştirilmiş verimlilik önerileri sunan dönem projesi.": "Projet de fin d'études offrant des analyses de conflits et des recommandations d'efficacité personnalisées.",
        "Hemen Ücretsiz Başla": "Commencer Gratuitement",
        "AI Zaman Asistanı": "Assistant Temporel IA",
        "AKTİF": "ACTIF",
        "Dönem Projesi Teslimi": "Remise du Projet",
        "Yapay Zeka Uyarısı:": "Alerte de l'IA :",
        "Zamanlama planınızda herhangi bir çakışma bulunmamaktadır. Günlük hedeflerinize ulaşmak için hazırsınız!": "Aucun conflit dans votre emploi du temps. Vous êtes prêt !",
        "Profil Fotoğrafını Değiştir": "Changer de Photo de Profil",
        "Fotoğraf Seç": "Choisir une Photo",
        "Dosya seçilmedi": "Aucun fichier sélectionné",
        "Desteklenen formatlar: PNG, JPG, JPEG, GIF (Maks. 2MB)": "Formats supportés : PNG, JPG, JPEG, GIF (Max. 2 Mo)",
        "Değişiklikleri Kaydet": "Enregistrer les Modifications",
        "AI Sohbet Asistanı": "Assistant Chat IA",
        " Flask Uygulamasını Sun": "Présenter l'Application Flask",
        "Panele Geri Dön": "Retour au Tableau de Bord"
    },
    "es": {
        "Gemini %(model_name)s Aktif": "Gemini %(model_name)s Activo",
        "AI Simülasyon Modu Aktif": "Modo de Simulación de IA Activo",
        "Geçmişi Temizle": "Limpiar Historial",
        "AI Simülasyon Modu:": "Modo de Simulación de IA:",
        "Şu an sunucuda bir Gemini API Anahtarı girilmediği için çevrimdışı simülasyon modu aktiftir. Asistana selam verebilir, planınızı sıralamasını veya çakışmaları bulmasını isteyebilirsiniz. Gerçek üretken yapay zekayı denemek için .env dosyanıza GEMINI_API_KEY ekleyebilirsiniz.": "El modo de simulación fuera de línea está activo porque no se ha introducido ninguna clave API de Gemini en el servidor. Puede saludar al asistente, pedirle que ordene su plan o que busque conflictos. Para probar la IA generativa real, puede agregar GEMINI_API_KEY a su archivo .env.",
        "Merhaba <strong>%(username)s</strong>! Ben senin akıllı planlama asistanın <strong>Glide AI</strong>.": "¡Hola <strong>%(username)s</strong>! Soy tu asistente de planificación inteligente <strong>Glide AI</strong>.",
        "Bugün yapılacak tüm görevlerini inceledim. Günlük işlerini planlamak, saat çakışmalarını çözmek veya o anki motivasyonuna göre zaman çizelgeni düzenlemek için buradayım.": "He revisado todas tus tareas de hoy. Estoy aquí para planificar tu trabajo diario, resolver conflictos de horarios u organizar tu cronograma según tu motivación actual.",
        "Bugün kendini nasıl hissediyorsun? Günün en verimli saatlerini hangi işlere ayırmak istersin? Yaz bana, planını karşılıklı konuşarak güncelleyelim!": "¿Cómo te sientes hoy? ¿A qué tareas te gustaría dedicar tus horas más productivas? ¡Escríbeme, actualicemos tu plan hablando juntos!",
        "Günlük planımdaki saat çakışmalarını kontrol eder misin?": "¿Podrías comprobar los conflictos de horario en mi plan diario?",
        "Çakışmaları Bul": "Buscar Conflictos",
        "Görevlerimi öncelik sırasına göre dizer misin?": "¿Podrías ordenar mis tareas por prioridad?",
        "Görevleri Sırala": "Ordenar Tareas",
        "Bugünkü planımı optimize etmek ve verimlilik tavsiyesi almak istiyorum.": "Quiero optimizar mi plan de hoy y obtener consejos de productividad.",
        "Verimlilik Önerileri": "Consejos de Productividad",
        "Bugün kendimi biraz yorgun hissediyorum, planımı esnek periyotlara çeker misin?": "¿Podrías ajustar mi plan a periodos flexibles hoy que me siento cansado?",
        "Esnek Plan İstiyorum": "Quiero un Plan Flexible",
        "Asistan ile konuşun, planınızı isteyin...": "Habla con el asistente, solicita tu plan...",
        "Sohbet geçmişinizi tamamen temizlemek istediğinize emin misiniz?": "¿Estás seguro de que deseas limpiar completamente tu historial de chat?",
        "Hata:": "Error:",
        "İşlem gerçekleştirilemedi.": "No se pudo realizar la operación.",
        "Bir hata oluştu": "Ocurrió un error",
        "Bir hata oluştu.": "Ocurrió un error.",
        "AI Asistanı": "Asistente de IA",
        "Planlama Asistanı": "Asistente de Planificación",
        "AI Akıllı Planlayıcı": "Planificador de IA Inteligente",
        "Yapay zeka tarafından üretilen zaman analizi ve verimlilik önerileri.": "Análisis de tiempo y recomendaciones de eficiencia generados por IA.",
        "Analizi Yenile": "Actualizar Análisis",
        "Yapay Zeka Analiz Raporu": "Reporte de Análisis de IA",
        "Oluşturulma Zamanı:": "Creado en:",
        "Henüz Bir Rapor Yok": "Sin Reportes Aún",
        "Zaman planınızı optimize etmek ve çakışma raporu almak için lütfen analizi başlatın.": "Inicie el análisis para optimizar su horario y obtener reportes de conflicto.",
        "Akıllı Öncelik Sıralaması": "Orden Inteligente de Prioridad",
        "Görevleriniz, yapay zekanın önerdiği şekilde periyot, öncelik derecesi ve saat baz alınarak verimlilik odaklı sıralanmıştır.": "Sus tareas están ordenadas por periodo, prioridad y hora para mayor eficiencia, según lo recomendado por la IA.",
        "Görev Tanımlanmamış": "Sin Tareas Definidas",
        "Öncelik sıralaması görebilmek için önce görevlerinizi ekleyin.": "Agregue sus tareas primero para ver su orden de prioridad.",
        "örn. Python Projesi Hazırla": "ej. Preparar Proyecto Python",
        "Görev detaylarını buraya yazın...": "Escriba los detalles de la tarea aquí...",
        "Tümü": "Todo",
        "Öncelik:": "Prioridad:",
        "\\%(query)s\\ için arama sonuçları": "Resultados de búsqueda para \"%(query)s\"",
        "Bu görevi silmek istediğinize emin misiniz?": "¿Está seguro de que desea eliminar esta tarea?",
        "Aradığınız kriterlere uygun görev bulunamadı": "No se encontraron tareas que coincidan con sus criterios",
        "Lütfen arama teriminizi değiştirip tekrar deneyin.": "Cambie su término de búsqueda e intente nuevamente.",
        "Yeni planlar yapmak için sol paneldeki görev formunu kullanabilirsiniz.": "Puede usar el formulario de tareas en el panel izquierdo para crear nuevos planes.",
        "Sunucuyla bağlantı kurulurken hata oluştu.": "Ocurrió un error al conectar con el servidor.",
        "Hesabınıza erişmek için bilgilerinizi girin.": "Ingrese sus datos para acceder a su cuenta.",
        "kullanici_adi": "nombre_de_usuario",
        "Kullanmaya başlamak için kaydolun.": "Regístrese para comenzar a usar la aplicación.",
        "Zaten üye misiniz?": "¿Ya es miembro?",
        "Giriş Yapın": "Iniciar Sesión",
        "Hesabınızın kayıtlı e-posta adresini girin.": "Ingrese el correo electrónico registrado.",
        "Sıfırlama Bağlantısı Gönder": "Enviar Enlace de Restablecimiento",
        "Giriş Sayfasına Dön": "Volver al Inicio",
        "Yeni Şifre Belirle": "Nueva Contraseña",
        "Hesabınız için yeni ve güçlü bir şifre girin.": "Ingrese una contraseña fuerte y nueva.",
        "Yeni Şifre": "Nueva Contraseña",
        "Şifremi Güncelle": "Actualizar Contraseña",
        "Ups! Bir şeyler ters gitti.": "¡Ups! Algo salió mal.",
        "Panelime Git": "Ir al Tablero",
        "Yapay Zeka Destekli Planlayıcı": "Planificador con IA",
        "Yapay Zeka Destekli Akıllı Zaman Yönetimi": "Gestión inteligente del tiempo con IA",
        "Zamanınızı": "Rediseña con",
        "Yapay Zeka": "la IA tu",
        "ile Yeniden Şekillendirin": "tiempo",
        "Spagetti kodlardan arınmış, modüler Flask mimarisiyle geliştirilmiş; çakışma analizleri ve kişiselleştirilmiş verimlilik önerileri sunan dönem projesi.": "Proyecto final con análisis de conflictos y optimización.",
        "Hemen Ücretsiz Başla": "Comenzar Gratis",
        "AI Zaman Asistanı": "Asistente de Tiempo de IA",
        "AKTİF": "ACTIVO",
        "Dönem Projesi Teslimi": "Entrega del Proyecto Final",
        "Yapay Zeka Uyarısı:": "Alerta de IA:",
        "Zamanlama planınızda herhangi bir çakışma bulunmamaktadır. Günlük hedeflerinize ulaşmak için hazırsınız!": "Sin conflictos en tu horario. ¡Listo!",
        "Profil Fotoğrafını Değiştir": "Cambiar Foto de Perfil",
        "Fotoğraf Seç": "Elegir Foto",
        "Dosya seçilmedi": "Sin archivo",
        "Desteklenen formatlar: PNG, JPG, JPEG, GIF (Maks. 2MB)": "Formatos: PNG, JPG, JPEG, GIF (Máx. 2MB)",
        "Değişiklikleri Kaydet": "Guardar Cambios",
        "AI Sohbet Asistanı": "Asistente Chat IA",
        " Flask Uygulamasını Sun": "Presentar Aplicación Flask",
        "Panele Geri Dön": "Volver al Tablero"
    },
    "tr": {
        "Gemini %(model_name)s Aktif": "Gemini %(model_name)s Aktif",
        "AI Simülasyon Modu Aktif": "AI Simülasyon Modu Aktif",
        "Geçmişi Temizle": "Geçmişi Temizle",
        "AI Simülasyon Modu:": "AI Simülasyon Modu:",
        "Şu an sunucuda bir Gemini API Anahtarı girilmediği için çevrimdışı simülasyon modu aktiftir. Asistana selam verebilir, planınızı sıralamasını veya çakışmaları bulmasını isteyebilirsiniz. Gerçek üretken yapay zekayı denemek için .env dosyanıza GEMINI_API_KEY ekleyebilirsiniz.": "Şu an sunucuda bir Gemini API Anahtarı girilmediği için çevrimdışı simülasyon modu aktiftir. Asistana selam verebilir, planınızı sıralamasını veya çakışmaları bulmasını isteyebilirsiniz. Gerçek üretken yapay zekayı denemek için .env dosyanıza GEMINI_API_KEY ekleyebilirsiniz.",
        "Merhaba <strong>%(username)s</strong>! Ben senin akıllı planlama asistanın <strong>Glide AI</strong>.": "Merhaba <strong>%(username)s</strong>! Ben senin akıllı planlama asistanın <strong>Glide AI</strong>.",
        "Bugün yapılacak tüm görevlerini inceledim. Günlük işlerini planlamak, saat çakışmalarını çözmek veya o anki motivasyonuna göre zaman çizelgeni düzenlemek için buradayım.": "Bugün yapılacak tüm görevlerini inceledim. Günlük işlerini planlamak, saat çakışmalarını çözmek veya o anki motivasyonuna göre zaman çizelgeni düzenlemek için buradayım.",
        "Bugün kendini nasıl hissediyorsun? Günün en verimli saatlerini hangi işlere ayırmak istersin? Yaz bana, planını karşılıklı konuşarak güncelleyelim!": "Bugün kendini nasıl hissediyorsun? Günün en verimli saatlerini hangi işlere ayırmak istersin? Yaz bana, planını karşılıklı konuşarak güncelleyelim!",
        "Günlük planımdaki saat çakışmalarını kontrol eder misin?": "Günlük planımdaki saat çakışmalarını kontrol eder misin?",
        "Çakışmaları Bul": "Çakışmaları Bul",
        "Görevlerimi öncelik sırasına göre dizer misin?": "Görevlerimi öncelik sırasına göre dizer misin?",
        "Görevleri Sırala": "Görevleri Sırala",
        "Bugünkü planımı optimize etmek ve verimlilik tavsiyesi almak istiyorum.": "Bugünkü planımı optimize etmek ve verimlilik tavsiyesi almak istiyorum.",
        "Verimlilik Önerileri": "Verimlilik Önerileri",
        "Bugün kendimi biraz yorgun hissediyorum, planımı esnek periyotlara çeker misin?": "Bugün kendimi biraz yorgun hissediyorum, planımı esnek periyotlara çeker misin?",
        "Esnek Plan İstiyorum": "Esnek Plan İstiyorum",
        "Asistan ile konuşun, planınızı isteyin...": "Asistan ile konuşun, planınızı isteyin...",
        "Sohbet geçmişinizi tamamen temizlemek istediğinize emin misiniz?": "Sohbet geçmişinizi tamamen temizlemek istediğinize emin misiniz?",
        "Hata:": "Hata:",
        "İşlem gerçekleştirilemedi.": "İşlem gerçekleştirilemedi.",
        "Bir hata oluştu": "Bir hata oluştu",
        "Bir hata oluştu.": "Bir hata oluştu.",
        "AI Asistanı": "AI Asistanı",
        "Planlama Asistanı": "Planlama Asistanı",
        "AI Akıllı Planlayıcı": "AI Akıllı Planlayıcı",
        "Yapay zeka tarafından üretilen zaman analizi ve verimlilik önerileri.": "Yapay zeka tarafından üretilen zaman analizi ve verimlilik önerileri.",
        "Analizi Yenile": "Analizi Yenile",
        "Yapay Zeka Analiz Raporu": "Yapay Zeka Analiz Raporu",
        "Oluşturulma Zamanı:": "Oluşturulma Zamanı:",
        "Henüz Bir Rapor Yok": "Henüz Bir Rapor Yok",
        "Zaman planınızı optimize etmek ve çakışma raporu almak için lütfen analizi başlatın.": "Zaman planınızı optimize etmek ve çakışma raporu almak için lütfen analizi başlatın.",
        "Akıllı Öncelik Sıralaması": "Akıllı Öncelik Sıralaması",
        "Görevleriniz, yapay zekanın önerdiği şekilde periyot, öncelik derecesi ve saat baz alınarak verimlilik odaklı sıralanmıştır.": "Görevleriniz, yapay zekanın önerdiği şekilde periyot, öncelik derecesi ve saat baz alınarak verimlilik odaklı sıralanmıştır.",
        "Görev Tanımlanmamış": "Görev Tanımlanmamış",
        "Öncelik sıralaması görebilmek için önce görevlerinizi ekleyin.": "Öncelik sıralaması görebilmek için önce görevlerinizi ekleyin.",
        "örn. Python Projesi Hazırla": "örn. Python Projesi Hazırla",
        "Görev detaylarını buraya yazın...": "Görev detaylarını buraya yazın...",
        "Tümü": "Tümü",
        "Öncelik:": "Öncelik:",
        "\\%(query)s\\ için arama sonuçları": "\"%(query)s\" için arama sonuçları",
        "Bu görevi silmek istediğinize emin misiniz?": "Bu görevi silmek istediğinize emin misiniz?",
        "Aradığınız kriterlere uygun görev bulunamadı": "Aradığınız kriterlere uygun görev bulunamadı",
        "Lütfen arama teriminizi değiştirip tekrar deneyin.": "Lütfen arama teriminizi değiştirip tekrar deneyin.",
        "Yeni planlar yapmak için sol paneldeki görev formunu kullanabilirsiniz.": "Yeni planlar yapmak için sol paneldeki görev formunu kullanabilirsiniz.",
        "Sunucuyla bağlantı kurulurken hata oluştu.": "Sunucuyla bağlantı kurulurken hata oluştu.",
        "Hesabınıza erişmek için bilgilerinizi girin.": "Hesabınıza erişmek için bilgilerinizi girin.",
        "kullanici_adi": "kullanici_adi",
        "Kullanmaya başlamak için kaydolun.": "Kullanmaya başlamak için kaydolun.",
        "Zaten üye misiniz?": "Zaten üye misiniz?",
        "Giriş Yapın": "Giriş Yapın",
        "Hesabınızın kayıtlı e-posta adresini girin.": "Hesabınızın kayıtlı e-posta adresini girin.",
        "Sıfırlama Bağlantısı Gönder": "Sıfırlama Bağlantısı Gönder",
        "Giriş Sayfasına Dön": "Giriş Sayfasına Dön",
        "Yeni Şifre Belirle": "Yeni Şifre Belirle",
        "Hesabınız için yeni ve güçlü bir şifre girin.": "Hesabınız için yeni ve güçlü bir şifre girin.",
        "Yeni Şifre": "Yeni Şifre",
        "Şifremi Güncelle": "Şifremi Güncelle",
        "Ups! Bir şeyler ters gitti.": "Ups! Bir şeyler ters gitti.",
        "Panelime Git": "Panelime Git",
        "Yapay Zeka Destekli Planlayıcı": "Yapay Zeka Destekli Planlayıcı",
        "Yapay Zeka Destekli Akıllı Zaman Yönetimi": "Yapay Zeka Destekli Akıllı Zaman Yönetimi",
        "Zamanınızı": "Zamanınızı",
        "Yapay Zeka": "Yapay Zeka",
        "ile Yeniden Şekillendirin": "ile Yeniden Şekillendirin",
        "Spagetti kodlardan arınmış, modüler Flask mimarisiyle geliştirilmiş; çakışma analizleri ve kişiselleştirilmiş verimlilik önerileri sunan dönem projesi.": "Spagetti kodlardan arınmış, modüler Flask mimarisiyle geliştirilmiş; çakışma analizleri ve kişiselleştirilmiş verimlilik önerileri sunan dönem projesi.",
        "Hemen Ücretsiz Başla": "Hemen Ücretsiz Başla",
        "AI Zaman Asistanı": "AI Zaman Asistanı",
        "AKTİF": "AKTİF",
        "Dönem Projesi Teslimi": "Dönem Projesi Teslimi",
        "Yapay Zeka Uyarısı:": "Yapay Zeka Uyarısı:",
        "Zamanlama planınızda herhangi bir çakışma bulunmamaktadır. Günlük hedeflerinize ulaşmak için hazırsınız!": "Zamanlama planınızda herhangi bir çakışma bulunmamaktadır. Günlük hedeflerinize ulaşmak için hazırsınız!",
        "Profil Fotoğrafını Değiştir": "Profil Fotoğrafını Değiştir",
        "Fotoğraf Seç": "Fotoğraf Seç",
        "Dosya seçilmedi": "Dosya seçilmedi",
        "Desteklenen formatlar: PNG, JPG, JPEG, GIF (Maks. 2MB)": "Desteklenen formatlar: PNG, JPG, JPEG, GIF (Maks. 2MB)",
        "Değişiklikleri Kaydet": "Değişiklikleri Kaydet",
        "AI Sohbet Asistanı": "AI Sohbet Asistanı",
        " Flask Uygulamasını Sun": "Flask Uygulamasını Sun",
        "Panele Geri Dön": "Panele Geri Dön"
    },
    "hi": {
        "Gemini %(model_name)s Aktif": "Gemini %(model_name)s सक्रिय",
        "AI Simülasyon Modu Aktif": "एआई सिमुलेशन मोड सक्रिय",
        "Geçmişi Temizle": "इतिहास साफ़ करें",
        "AI Simülasyon Modu:": "एआई सिमुलेशन मोड:",
        "Şu an sunucuda bir Gemini API Anahtarı girilmediği için çevrimdışı simülasyon modu aktiftir. Asistana selam verebilir, planınızı sıralamasını veya çakışmaları bulmasını isteyebilirsiniz. Gerçek üretken yapay zekayı denemek için .env dosyanıza GEMINI_API_KEY ekleyebilirsiniz.": "ऑफ़लाइन सिमुलेशन मोड सक्रिय है क्योंकि सर्वर पर कोई जेमिनी एपीआई कुंजी दर्ज नहीं है। आप सहायक को नमस्ते कह सकते हैं, उससे अपनी योजना को क्रमबद्ध करने या संघर्षों को खोजने के लिए कह सकते हैं। वास्तविक उत्पादक एआई का प्रयास करने के लिए, आप अपनी .env फ़ाइल में GEMINI_API_KEY जोड़ सकते हैं।",
        "Merhaba <strong>%(username)s</strong>! Ben senin akıllı planlama asistanın <strong>Glide AI</strong>.": "नमस्ते <strong>%(username)s</strong>! मैं आपका स्मार्ट प्लानिंग असिस्टेंट <strong>Glide AI</strong> हूँ।",
        "Bugün yapılacak tüm görevlerini inceledim. Günlük işlerini planlamak, saat çakışmalarını çözmek veya o anki motivasyonuna göre zaman çizelgeni düzenlemek için buradayım.": "मैंने आज के लिए आपके सभी कार्यों की समीक्षा की है। मैं यहाँ आपके दैनिक कार्य की योजना बनाने, समय के संघर्षों को हल करने, या आपकी वर्तमान प्रेरणा के आधार पर आपकी समयरेखा को व्यवस्थित करने के लिए हूँ।",
        "Bugün kendini nasıl hissediyorsun? Günün en verimli saatlerini hangi işlere ayırmak istersin? Yaz bana, planını karşılıklı konuşarak güncelleyelim!": "आज आप कैसा महसूस कर रहे हैं? आप अपने सबसे अधिक उत्पादक घंटे किन कार्यों को आवंटित करना चाहेंगे? मुझे लिखें, आइए मिलकर अपनी योजना को अपडेट करें!",
        "Günlük planımdaki saat çakışmalarını kontrol eder misin?": "क्या आप मेरी दैनिक योजना में समय के संघर्षों की जांच कर सकते हैं?",
        "Çakışmaları Bul": "संघर्ष खोजें",
        "Görevlerimi öncelik sırasına göre dizer misin?": "क्या आप मेरे कार्यों को प्राथमिकता के अनुसार व्यवस्थित कर सकते हैं?",
        "Görevleri Sırala": "कार्यों को क्रमबद्ध करें",
        "Bugünkü planımı optimize etmek ve verimlilik tavsiyesi almak istiyorum.": "मैं आज की अपनी योजना को अनुकूलित करना चाहता हूँ और उत्पादकता सलाह लेना चाहता हूँ।",
        "Verimlilik Önerileri": "उत्पादकता सुझाव",
        "Bugün kendimi biraz yorgun hissediyorum, planımı esnek periyotlara çeker misin?": "आज मैं थोड़ा थका हुआ महसूस कर रहा हूँ, क्या आप मेरी योजना को लचीली अवधियों में समायोजित कर सकते हैं?",
        "Esnek Plan İstiyorum": "मुझे लचीली योजना चाहिए",
        "Asistan ile konuşun, planınızı isteyin...": "सहायक से बात करें, अपनी योजना माँगें...",
        "Sohbet geçmişinizi tamamen temizlemek istediğinize emin misiniz?": "क्या आप वाकई अपना चैट इतिहास पूरी तरह से साफ़ करना चाहते हैं?",
        "Hata:": "त्रुटि:",
        "İşlem gerçekleştirilemedi.": "ऑपरेशन पूरा नहीं किया जा सका।",
        "Bir hata oluştu": "एक त्रुटि हुई",
        "Bir hata oluştu.": "एक त्रुटि हुई।",
        "AI Asistanı": "AI सहायक",
        "Planlama Asistanı": "योजना सहायक",
        "AI Akıllı Planlayıcı": "AI स्मार्ट योजनाकार",
        "Yapay zeka tarafından üretilen zaman analizi ve verimlilik önerileri.": "AI द्वारा उत्पन्न समय विश्लेषण और उत्पादकता सुझाव।",
        "Analizi Yenile": "विश्लेषण रीफ्रेश करें",
        "Yapay Zeka Analiz Raporu": "AI विश्लेषण रिपोर्ट",
        "Oluşturulma Zamanı:": "निर्माण समय:",
        "Henüz Bir Rapor Yok": "कोई रिपोर्ट नहीं",
        "Zaman planınızı optimize etmek ve çakışma raporu almak için lütfen analizi başlatın.": "अपनी योजना को अनुकूलित करने और संघर्ष रिपोर्ट प्राप्त करने के लिए कृपया विश्लेषण शुरू करें।",
        "Akıllı Öncelik Sıralaması": "स्मार्ट प्राथमिकता अनुक्रम",
        "Görevleriniz, yapay zekanın önerdiği şekilde periyot, öncelik derecesi ve saat baz alınarak verimlilik odaklı sıralanmıştır.": "आपके कार्य दक्षता के लिए अवधि, प्राथमिकता और समय के आधार पर व्यवस्थित किए गए हैं, जैसा कि AI द्वारा अनुशंसित है।",
        "Görev Tanımlanmamış": "कोई कार्य परिभाषित नहीं",
        "Öncelik sıralaması görebilmek için önce görevlerinizi ekleyin.": "प्राथमिकता अनुक्रम देखने के लिए पहले अपने कार्य जोड़ें।",
        "örn. Python Projesi Hazırla": "जैसे: पायथन प्रोजेक्ट तैयार करें",
        "Görev detaylarını buraya yazın...": "कार्य विवरण यहाँ लिखें...",
        "Tümü": "सभी",
        "Öncelik:": "प्राथमिकता:",
        "\\%(query)s\\ için arama sonuçları": "\"%(query)s\" के लिए खोज परिणाम",
        "Bu görevi silmek istediğinize emin misiniz?": "क्या आप वाकई इस कार्य को हटाना चाहते हैं?",
        "Aradığınız kriterlere uygun görev bulunamadı": "आपके मानदंडों से मेल खाने वाला कोई कार्य नहीं मिला",
        "Lütfen arama teriminizi değiştirip tekrar deneyin.": "कृपया अपना खोज शब्द बदलें और पुनः प्रयास करें।",
        "Yeni planlar yapmak için sol paneldeki görev formunu kullanabilirsiniz.": "नए प्लान बनाने के लिए आप बाएं पैनल पर मौजूद टास्क फॉर्म का इस्तेमाल कर सकते हैं।",
        "Sunucuyla bağlantı kurulurken hata oluştu.": "सर्वर से कनेक्ट करते समय एक त्रुटि हुई।",
        "Hesabınıza erişmek için bilgilerinizi girin.": "अपने खाते तक पहुँचने के लिए अपनी जानकारी दर्ज करें।",
        "kullanici_adi": "उपयोगकर्ता_नाम",
        "Kullanmaya başlamak için kaydolun.": "उपयोग शुरू करने के लिए साइन अप करें।",
        "Zaten üye misiniz?": "क्या आप पहले से सदस्य हैं?",
        "Giriş Yapın": "लॉग इन करें",
        "Hesabınızın kayıtlı e-posta adresini girin.": "अपने खाते का पंजीकृत ईमेल पता दर्ज करें।",
        "Sıfırlama Bağlantısı Gönder": "रीसेट लिंक भेजें",
        "Giriş Sayfasına Dön": "लॉगिन पेज पर लौटें",
        "Yeni Şifre Belirle": "नया पासवर्ड सेट करें",
        "Hesabınız için yeni ve güçlü bir şifre girin.": "अपने खाते के लिए एक नया और मजबूत पासवर्ड दर्ज करें।",
        "Yeni Şifre": "नया पासवर्ड",
        "Şifremi Güncelle": "मेरा पासवर्ड अपडेट करें",
        "Ups! Bir şeyler ters gitti.": "ओह! कुछ गलत हो गया।",
        "Panelime Git": "मेरे डैशबोर्ड पर जाएं",
        "Yapay Zeka Destekli Planlayıcı": "एआई-संचालित योजनाकार",
        "Yapay Zeka Destekli Akıllı Zaman Yönetimi": "एआई-संचालित स्मार्ट समय प्रबंधन",
        "Zamanınızı": "अपना समय",
        "Yapay Zeka": "कृत्रिम बुद्धिमत्ता",
        "ile Yeniden Şekillendirin": "के साथ पुनर्गठित करें",
        "Spagetti kodlardan arınmış, modüler Flask mimarisiyle geliştirilmiş; çakışma analizleri ve kişiselleştirilmiş verimlilik önerileri sunan dönem projesi.": "स्पैगेटी कोड से मुक्त, मॉड्यूलर फ्लास्क आर्किटेक्चर पर निर्मित एक टर्म प्रोजेक्ट, जिसमें संघर्ष विश्लेषण और व्यक्तिगत उत्पादकता सुझाव शामिल हैं।",
        "Hemen Ücretsiz Başla": "तुरंत मुफ्त में शुरू करें",
        "AI Zaman Asistanı": "एआई समय सहायक",
        "AKTİF": "सक्रिय",
        "Dönem Projesi Teslimi": "टर्म प्रोजेक्ट डिलीवरी",
        "Yapay Zeka Uyarısı:": "एआई चेतावनी:",
        "Zamanlama planınızda herhangi bir çakışma bulunmamaktadır. Günlük hedeflerinize ulaşmak için hazırsınız!": "आपके कार्यक्रम में कोई समय टकराव नहीं है। आप अपने दैनिक लक्ष्यों को प्राप्त करने के लिए तैयार हैं!",
        "Profil Fotoğrafını Değiştir": "प्रोफ़ाइल चित्र बदलें",
        "Fotoğraf Seç": "फोटो चुनें",
        "Dosya seçilmedi": "कोई फ़ाइल नहीं चुनी गई",
        "Desteklenen formatlar: PNG, JPG, JPEG, GIF (Maks. 2MB)": "समर्थित प्रारूप: PNG, JPG, JPEG, GIF (अधिकतम 2MB)",
        "Değişiklikleri Kaydet": "परिवर्तन सहेजें",
        "AI Sohbet Asistanı": "एआई चैट सहायक",
        " Flask Uygulamasını Sun": "फ्लास्क एप्लिकेशन प्रस्तुत करें",
        "Panele Geri Dön": "डैशबोर्ड पर वापस जाएं"
    },
    "ar": {
        "Gemini %(model_name)s Aktif": "Gemini %(model_name)s نشط",
        "AI Simülasyon Modu Aktif": "وضع محاكاة الذكاء الاصطناعي نشط",
        "Geçmişi Temizle": "مسح السجل",
        "AI Simülasyon Modu:": "وضع محاكاة الذكاء الاصطناعي:",
        "Şu an sunucuda bir Gemini API Anahtarı girilmediği için çevrimdışı simülasyon modu aktiftir. Asistana selam verebilir, planınızı sıralamasını veya çakışmaları bulmasını isteyebilirsiniz. Gerçek üretken yapay zekayı denemek için .env dosyanıza GEMINI_API_KEY ekleyebilirsiniz.": "وضع المحاكاة غير المتصل بالإنترنت نشط لأنه لم يتم إدخال مفتاح Gemini API على الخادم. يمكنك إلقاء التحية على المساعد، أو الطلب منه ترتيب خطتك أو العثور على التعارضات. لتجربة الذكاء الاصطناعي التوليدي الحقيقي، يمكنك إضافة GEMINI_API_KEY إلى ملف .env الخاص بك.",
        "Merhaba <strong>%(username)s</strong>! Ben senin akıllı planlama asistanın <strong>Glide AI</strong>.": "مرحباً <strong>%(username)s</strong>! أنا مساعد التخطيط الذكي الخاص بك <strong>Glide AI</strong>.",
        "Bugün yapılacak tüm görevlerini inceledim. Günlük işlerini planlamak, saat çakışmalarını çözmek veya o anki motivasyonuna göre zaman çizelgeni düzenlemek için buradayım.": "لقد راجعت جميع مهامك اليوم. أنا هنا للتخطيط لعملك اليومي، أو حل تعارضات الأوقات، أو تنظيم جدولك الزمني بناءً على طاقتك الحالية.",
        "Bugün kendini nasıl hissediyorsun? Günün en verimli saatlerini hangi işlere ayırmak istersin? Yaz bana, planını karşılıklı konuşarak güncelleyelim!": "كيف تشعر اليوم؟ ما هي المهام التي ترغب في تخصيص أكثر ساعاتك إنتاجية لها؟ اكتب لي، دعنا نحدث خطتك من خلال التحدث معاً!",
        "Günlük planımdaki saat çakışmalarını kontrol eder misin?": "هل يمكنك التحقق من تعارضات الوقت في خطتي اليومية؟",
        "Çakışmaları Bul": "العثور على التعارضات",
        "Görevlerimi öncelik sırasına göre dizer misin?": "هل يمكنك ترتيب مهامي حسب الأولوية؟",
        "Görevleri Sırala": "ترتيب المهام",
        "Bugünkü planımı optimize etmek ve verimlilik tavsiyesi almak istiyorum.": "أريد تحسين خطتي لليوم والحصول على نصائح إنتاجية.",
        "Verimlilik Önerileri": "نصائح الإنتاجية",
        "Bugün kendimi biraz yorgun hissediyorum, planımı esnek periyotlara çeker misin?": "أشعر بالتعب قليلاً اليوم، هل يمكنك ضبط خطتي إلى فترات مرنة؟",
        "Esnek Plan İstiyorum": "أريد خطة مرنة",
        "Asistan ile konuşun, planınızı isteyin...": "تحدث مع المساعد، واطلب خطتك...",
        "Sohbet geçmişinizi tamamen temizlemek istediğinize emin misiniz?": "هل أنت متأكد أنك تريد مسح سجل المحادثة بالكامل؟",
        "Hata:": "خطأ:",
        "İşlem gerçekleştirilemedi.": "تعذر إكمال العملية.",
        "Bir hata oluştu": "حدث خطأ ما",
        "Bir hata oluştu.": "حدث خطأ ما.",
        "AI Asistanı": "مساعد الذكاء الاصطناعي",
        "Planlama Asistanı": "مساعد التخطيط",
        "AI Akıllı Planlayıcı": "مخطط الذكاء الاصطناعي الذكي",
        "Yapay zeka tarafından üretilen zaman analizi ve verimlilik önerileri.": "تحليل الوقت وتوصيات الكفاءة الناتجة عن الذكاء الاصطناعي.",
        "Analizi Yenile": "تحديث التحليل",
        "Yapay Zeka Analiz Raporu": "تقرير تحليل الذكاء الاصطناعي",
        "Oluşturulma Zamanı:": "وقت الإنشاء:",
        "Henüz Bir Rapor Yok": "لا يوجد تقرير بعد",
        "Zaman planınızı optimize etmek ve çakışma raporu almak için lütfen analizi başlatın.": "يرجى بدء التحليل لتحسين جدولك الزمني والحصول على تقارير التعارض.",
        "Akıllı Öncelik Sıralaması": "ترتيب الأولويات الذكي",
        "Görevleriniz, yapay zekanın önerdiği şekilde periyot, öncelik derecesi ve saat baz alınarak verimlilik odaklı sıralanmıştır.": "تم ترتيب مهامك حسب الفترة والأولوية والوقت لتحقيق الكفاءة، بناءً على توصية الذكاء الاصطناعي.",
        "Görev Tanımlanmamış": "لم يتم تحديد أي مهمة",
        "Öncelik sıralaması görebilmek için önce görevlerinizi ekleyin.": "يرجى إضافة مهامك أولاً لمشاهدة ترتيب أولوياتها.",
        "örn. Python Projesi Hazırla": "مثال: إعداد مشروع بايثون",
        "Görev detaylarını buraya yazın...": "اكتب تفاصيل المهمة هنا...",
        "Tümü": "الكل",
        "Öncelik:": "الأولوية:",
        "\\%(query)s\\ için arama sonuçları": "نتائج البحث عن \"%(query)s\"",
        "Bu görevi silmek istediğinize emin misiniz?": "هل أنت متأكد أنك تريد حذف هذه المهمة؟",
        "Aradığınız kriterlere uygun görev bulunamadı": "لم يتم العثور على أي مهمة تطابق المعايير الخاصة بك",
        "Lütfen arama teriminizi değiştirip tekrar deneyin.": "يرجى تغيير مصطلح البحث والمحاولة مرة أخرى.",
        "Yeni planlar yapmak için sol paneldeki görev formunu kullanabilirsiniz.": "يمكنك استخدام نموذج المهمة في اللوحة اليسرى لإنشاء خطط جديدة.",
        "Sunucuyla bağlantı kurulurken hata oluştu.": "حدث خطأ أثناء الاتصال بالخادم.",
        "Hesabınıza erişmek için bilgilerinizi girin.": "أدخل معلوماتك للوصول إلى حسابك.",
        "kullanici_adi": "اسم_المستخدم",
        "Kullanmaya başlamak için kaydolun.": "سجل الآن لبدء استخدام التطبيق.",
        "Zaten üye misiniz?": "هل أنت عضو بالفعل؟",
        "Giriş Yapın": "تسجيل الدخول",
        "Hesabınızın kayıtlı e-posta adresini girin.": "أدخل البريد الإلكتروني المسجل لحسابك.",
        "Sıfırlama Bağlantısı Gönder": "إرسال رابط إعادة التعيين",
        "Giriş Sayfasına Dön": "العودة إلى صفحة تسجيل الدخول",
        "Yeni Şifre Belirle": "تعيين كلمة مرور جديدة",
        "Hesabınız için yeni ve güçlü bir şifre girin.": "أدخل كلمة مرور جديدة وقوية لحسابك.",
        "Yeni Şifre": "كلمة مرور جديدة",
        "Şifremi Güncelle": "تحديث كلمة المرور الخاصة بي",
        "Ups! Bir şeyler ters gitti.": "أوبس! حدث خطأ ما.",
        "Panelime Git": "الذهاب إلى لوحة التحكم الخاصة بي",
        "Yapay Zeka Destekli Planlayıcı": "مخطط مدعوم بالذكاء الاصطناعي",
        "Yapay Zeka Destekli Akıllı Zaman Yönetimi": "إدارة ذكية للوقت مدعومة بالذكاء الاصطناعي",
        "Zamanınızı": "وقتك",
        "Yapay Zeka": "الذكاء الاصطناعي",
        "ile Yeniden Şekillendirin": "أعد تشكيل",
        "Spagetti kodlardan arınmış, modüler Flask mimarisiyle geliştirilmiş; çakışma analizleri ve kişiselleştirilmiş verimlilik önerileri sunan dönem projesi.": "مشروع نهاية الفصل الدراسي المبني على بنية فلاسك مجزأة وخالية من الأكواد غير المنظمة، ويضم تحليل التعارضات ونصائح الكفاءة الشخصية.",
        "Hemen Ücretsiz Başla": "ابدأ الآن مجاناً",
        "AI Zaman Asistanı": "مساعد الوقت بالذكاء الاصطناعي",
        "AKTİF": "نشط",
        "Dönem Projesi Teslimi": "تسليم مشروع الفصل الدراسي",
        "Yapay Zeka Uyarısı:": "تنبيه الذكاء الاصطناعي:",
        "Zamanlama planınızda herhangi bir çakışma bulunmamaktadır. Günlük hedeflerinize ulaşmak için hazırsınız!": "لا توجد تعارضات في جدولك الزمني. أنت مستعد لتحقيق أهدافك اليومية!",
        "Profil Fotoğrafını Değiştir": "تغيير صورة الملف الشخصي",
        "Fotoğraf Seç": "اختر صورة",
        "Dosya seçilmedi": "لم يتم اختيار أي ملف",
        "Desteklenen formatlar: PNG, JPG, JPEG, GIF (Maks. 2MB)": "الصيغ المدعومة: PNG, JPG, JPEG, GIF (بحد أقصى 2 ميجابايت)",
        "Değişiklikleri Kaydet": "حفظ التغييرات",
        "AI Sohbet Asistanı": "مساعد الدردشة بالذكاء الاصطناعي",
        " Flask Uygulamasını Sun": "تقديم تطبيق Flask",
        "Panele Geri Dön": "العودة إلى لوحة التحكم"
    }
}

def update_po_file(lang, po_path):
    with open(po_path, 'r', encoding='utf-8') as f:
        content = f.read()

    blocks = re.split(r'\n\n', content)
    updated_blocks = []
    lang_translations = new_translations.get(lang, {})

    for block in blocks:
        block_strip = block.strip()
        if not block_strip:
            continue
        
        # Parse block
        lines = block_strip.split('\n')
        msgid_lines = []
        in_msgid = False
        msgstr_idx = -1
        
        for idx, line in enumerate(lines):
            line_str = line.strip()
            if line_str.startswith('msgid'):
                in_msgid = True
                msgid_lines.append(line_str[5:].strip())
            elif line_str.startswith('msgstr'):
                in_msgid = False
                msgstr_idx = idx
            elif line_str.startswith('"') and in_msgid:
                msgid_lines.append(line_str)
        
        msgid = "".join(msgid_lines).replace('"', '')
        
        if not msgid:
            updated_blocks.append(block_strip)
            continue
        
        # If we have a translation for this msgid
        if msgid in lang_translations:
            # Remove "fuzzy" flags
            lines = [l for l in lines if 'fuzzy' not in l]
            
            # Find the new index of msgstr after fuzzy lines are removed
            msgstr_idx = -1
            for idx, line in enumerate(lines):
                if line.strip().startswith('msgstr'):
                    msgstr_idx = idx
                    break
            
            # Format and set the translation
            translation_val = lang_translations[msgid].replace('"', '\\"')
            if msgstr_idx != -1:
                lines = lines[:msgstr_idx] + [f'msgstr "{translation_val}"']
            
            block_strip = "\n".join(lines)
            
        updated_blocks.append(block_strip)

    # Write back the updated content
    new_content = "\n\n".join(updated_blocks) + "\n"
    with open(po_path, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f"Updated {lang} PO catalog successfully.")

if __name__ == "__main__":
    for lang in ['tr', 'en', 'es', 'fr', 'hi', 'ar']:
        po_path = f"app/translations/{lang}/LC_MESSAGES/messages.po"
        if os.path.exists(po_path):
            update_po_file(lang, po_path)
